# Nombre de la aplicación
spring.application.name=vet-discovery-service

# Puerto oficial de Eureka
server.port=8761

# Configuración del servidor (No se registra a sí mismo)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false